beaker/ext/database.py

As commented by Juraj Variny in the Bitbucket repo, DatabaseNamespaceManager has the same issue as MemcachedNamespaceManager. This applies the same fix.

Same fix as commit 50a525ca1e, but for DatabaseNamespaceManager

---

beaker/docs/sessions.rst

I've spent a while trying to undestand why sessions example does not work out-of-the-box. After googling "KeyError beaker.session" I've found the discussion https://groups.google.com/forum/#!topic/modwsgi/lyRhHIr48nk where people pointed out to this misleading inaccuracy. We should explain to newcomer that old handler ``simple_app`` is overrided by new one created by Beaker's Middleware.

Clarify wsgi_app object purpose in example

---

beaker/docs/configuration.rst
beaker/session.py
beaker/util.py

Addresses issue #36 (which in turn addressed issue #35)

Added json as an option for cookie serialization

---

beaker/util.py

Previous patch was not using the method parameter in the deserialize function and instead attempting to depickle first, then if that failed fallback to json.  This means the security issue was not fixed, as pickle was still being called.

Updated deserialize function to use method parameter first

---

beaker/ext/memcached.py
tests/test_memcached.py

When using pylibmc as the memcache_module, each namespace gets its own instance of ThreadMappedPool. This causes a separate connection to the same memcached url for every namespace. This change makes sure that pools are shared between different namespaces the same way that clients are shared, and reduces the number of open connections when using pylibmc with multiple namespaces.

share instances of pylibmc.ThreadMappedPool in PyLibMCNamespaceManager

---

beaker/session.py

This change is backwards-compatible. 
FYI: I am planning a cookie subclass that will allow an upgrade of cookie expiry policy after login. I could do that in beaker, in a separate pull request, or in my own project, tell me what you prefer.

Configure the session subclass that will be proxied by the SessionObject.

---

CHANGELOG
beaker/docs/configuration.rst
beaker/docs/sessions.rst
beaker/middleware.py
beaker/session.py
beaker/util.py
tests/test_session.py

On sites that aren't using `session[_accessed_time]` or `session.last_accessed`, saving the session at the end of every request is wasted work. On big sites this can become a fair amount of load on a data store.
This adds an option to turn off access time storage, in which case if there aren't other changes to the session, it doesn't need to be written at all. It defaults to saving access times for backwards compatibility.

Add save_accessed_time option

---

beaker/cache.py

In Python 2.6 and 2.7, `io.StringIO` class is available but it is not compatible
with `String.StringIO` class.
* `io.StringIO` class accepts unicode string.
* `StringIO.StringIO` class accepts bytes string.
Therefore `StringIO.StringIO` class should be imported prior to `io.StringIO`.
Otherwise, `traceback.print_exc(file=tb)` (line 107) will raise TypeError.
For example:
```
File "/opt/python/blue_env/local/lib/python2.7/site-packages/Beaker-1.8.0-py2.7.egg/beaker/cache.py", line 107, in _init
traceback.print_exc(file=tb)
File "/usr/lib/python2.7/traceback.py", line 241, in print_exc
print_exception(etype, value, tb, limit, file)
File "/usr/lib/python2.7/traceback.py", line 132, in print_exception
_print(file, 'Traceback (most recent call last):')
File "/usr/lib/python2.7/traceback.py", …
```

fix to import StringIO.StringIO first

---

beaker/session.py
tests/test_cookie_expires.py

This is straightforward: Currently, if I set the cookie expiry to none after having set it to some other value, nothing happens.

Allow to reset the cookie expire to no expiry

---

beaker/session.py
beaker/util.py
tests/test_cookie_only.py

- Instead of `data_serializer`, callers can now pass a custom serializer object. That object can be anything with `loads` and `dumps` methods.
- data_serializer still supported for compatibility
- Also, error on unknown data serializer types instead of silently falling back to pickle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bbangert/beaker/99)

Allow custom serializer objects

---

beaker/docs/sessions.rst

The original sample has two minor issues that are simply annoying and can be fixed right away:
- you don't see what gets deleted (in case you want to put this into a logger)
- it always errors on the directories in the structure

Slightly more production-ready expiration sample

---

setup.py

pycryptodome is a maintained fork of pycrypto. They are mostly
API-compatible (and use the same package name, i.e. meant to be
a drop-in replacement), and AFAICS the little bit of API that Beaker
uses is fully compatible.
Therefore, list pycryptodome as another extra dependency. Furthermore,
since pycrypto is dead and being phased out whenever possible, use
pycryptodome for tests instead of it.

Allow using pycryptodome, and prefer it over pycrypto

---

beaker/docs/conf.py
beaker/docs/configuration.rst
beaker/docs/index.rst
beaker/session.py

The conf.py contained theme settings that broke the build with lates Sphinx and
that are also not relevant to the now used RTD theme.
Mention Redis and MongoDB as available backends since I've missed them myself
when looking at the docs.
Fix markup in one docstring that generated an RST error.

Fix docs building and document Redis/MongoDB

---

beaker/container.py

If a process is interrupted while saving cached data it could end up saving a partial file. This results in an exception being thrown later due to the corrupted cache.
This PR fixes this by saving the data to a temporary file and moving it into place once writing has completed. On posix systems the `rename` operation is atomic, so the system will either successfully move the file or fail- there will be no corruption.
Unfortunately the rename operations are not atomic on Windows, so this PR explicitly checks for a posix system or it will fall back on the previous behavior.

On posix systems write to tmp file before moving into place

---

beaker/container.py
beaker/util.py

This is a continuation of my efforts to deal with #134.
While buffering to a separate file and then moving it into location works for posix based systems, the lack of atomic move support on Windows and the fact that it will fail with an exception if the file already exists makes the solution not viable for that platform.
There are some complex ways that this can be dealt with, but they would have a negative performance hit (and I don't care enough about people who deploy to windows systems to devote the time to this).
Short of that, this PR reduces the time spent writing the file which in turn reduces the chances of corruption occurring. It does this by buffering the pickled output to a string rather than using the pickler's built in "write to file" system (which writes as the pickling …

create new `safe_write` function, buffer pickling on all platforms

---

beaker/ext/redisnm.py
beaker/session.py

Hey,
I was trying to figure out what is the best way to clean up old / unused session data from Redis backend. I found that the basic mechanics for setting expiration time is there, but there's no way to use it from layers above. With that change, I'm able to just pass `expiretime` into Middleware, and voila - keys in reds are having expiration time set! :)
Example usage of middleware:
```
app = SessionMiddleware(app, config, expiretime=5000)
```
Would be great if you could merge this change.
Thanks!
Kacper.

Ability to pass expiretime into RedisNamespaceManager

---

beaker/session.py

In the absence of AES support by the cryptographic module, an exception was thrown at session creation time.

Fix session creation without encryption (no aes)

---

beaker/ext/redisnm.py

Set value and expire flag is atomic now.
Otherwise in my system, when a lock value is set, but my system restart before the lock value is given the expire time, the lock will be a deadlock.

Fix: A true way to set redis expire time

---

beaker/session.py
tests/test_cookie_only.py

#159 adds support for the SameSite flag in cookie sessions, but does not set this option when the cookie is created. As a result, the `session.samesite` option does not actually set the SameSite flag in many cases. This resolves the above issue.

Set samesite cookie attribute on cookie creation

---

beaker/session.py
tests/test_cookie_only.py

CookieSession does not properly apply the `cookie_path` configuration option, causing the resulting cookie to be set for the default path instead.
This happens directly after initialization since this does not set the internal dict item associated with the `_path` key. It also happens after calling `delete` since this will clear the dict items.
The attribute `_path` should be used in `_create_cookie` instead as is done in `_set_cookie_values`.

Fix path for CookieSession

---

beaker/docs/configuration.rst

The `url` setting in https://beaker.readthedocs.io/en/latest/configuration.html#options-for-sessions-and-caching is not formatted correctly.

Fix formatting issue in the configuration doc

---

README.rst

The URL was updated in the GitHub repo description as of #89 and in the `setup.py` in #104 but has not been updated in the README yet, which is published to PyPI as the package description and displayed (obviously) on GitHub. 🧹

Use `beaker.readthedocs.io` in `README.rst`

---

beaker/session.py
tests/test_session.py

Unittest using the file namespace manager also provided. I haven't run tests for mongodb and all combinations of other drivers so I'm assuming they will run based on the fact that it's a base64 encoded string and everyone should be able to insert a string.
This commit will likely invalidate all sessions once deployed due to the fact that all sessions now get base64 encoded when written in storage (and decoded back) vs the previous situation of only encrypted sessions getting base64 encoded.

Fixed issue #122 - Session ignores deserializer json

---

beaker/session.py

Session ID generation preferentially uses the [uuid module](https://docs.python.org/2.7/library/uuid.html), which was added in Python 2.5.
Beaker has a fallback — implemented in 2011 — that uses a different approach when `import uuid` fails. Support for Python 2.4 and 2.5 was dropped in 2015, so all versions of Python currently supported by Beaker have the uuid module. This PR removes the now-unnecessary fallback.

Remove ID generation fallback for when the uuid module is not found

---

.travis.yml
beaker/cache.py
beaker/util.py
setup.cfg
setup.py
tests/test_cache.py
tests/test_cache_decorator.py
tests/test_cachemanager.py
tests/test_container.py
tests/test_cookie_domain_only.py
tests/test_cookie_expires.py
tests/test_cookie_only.py
tests/test_database.py
tests/test_domain_setting.py
tests/test_increment.py
tests/test_managers/base.py
tests/test_memcached.py
tests/test_namespacing.py
tests/test_session.py
tests/test_sqla.py
tests/test_synchronizer.py
tests/test_unicode_cache_keys.py

Port testing from nose to pytest.

---

beaker/session.py
tests/test_session.py

Session.load does not properly handle state after .delete and .save was called.
This happens when user logs out, but saves session id, and then tries to use it again.

Fix issue #180 - KeyError when loading deleted session

---

beaker/synchronization.py

switch to snakecase for threading related functions to clear deprecation warning in python 3.10

---

beaker/crypto/nsscrypto.py
beaker/middleware.py

There are small typos in:
- beaker/crypto/nsscrypto.py
- beaker/middleware.py
Fixes:
- Should read `initialize` rather than `intialize`.
- Should read `particular` rather than `particluar`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos
